### ISSUE TITLE
does this addon work with other admins like the "info" addon?

### ISSUE THREAD

**Issue by kevinbarabash** [storybooks/addon-jsx#32]
I'm curious b/c this addon requires switching from `add` to `addWithJsx`.

**Comment by Regaddi** [comment]
When using this addon together with https://github.com/storybooks/storybook/tree/master/addons/info then the output in the JSX Panel contains a lot more (basically all added info + boilerplate).

Example:

```jsx
(storiesOf('Common/Button', module))
  .addWithJSX(
    'submit',
    wInfo(`
    ### Notes

    It's a simple submit button.

    ### Usage

    ~~~js
    <Button type="submit">Submit</Button>
    ~~~`)(() => <Button type="submit">Submit</Button>)
  )
);
```

Output:

```jsx
<Story
  PropTable={function (props) {
    if (!props.type) {
      // eslint-disable-line
      return null;
    }

    var type = props.type;
    var propDefinitionsMap = hasDocgen(type) ? propsFromDocgen(type) : propsFromPropTypes(type);
    var propDefinitions = Object.values(propDefinitionsMap);
    return _react.default.createElement(Component, (0, _extends2.default)({
      propDefinitions: propDefinitions
    }, props));
  }}
  components={{
    a: function A(_ref4) {
    var href = _ref4.href,
        children = _ref4.children;
    var style = {
      color: '#3498db'
    };
    return _react.default.createElement("a", {
      href: href,
      target: "_blank",
      rel: "noopener noreferrer",
      style: style
    }, children);
  },
    code: function Code() {
      (0, _classCallCheck2.default)(this, Code);
      return (0, _possibleConstructorReturn2.default)(this, (0, _getPrototypeOf2.default)(Code).apply(this, arguments));
    },
    h1: function H1(_ref) {
    var id = _ref.id,
        children = _ref.children;
    var styles = (0, _objectSpread2.default)({}, _components.baseFonts, {
      borderBottom: '1px solid #eee',
      fontWeight: 600,
      margin: 0,
      padding: 0,
      fontSize: '40px'
    });
    return _react.default.createElement("h1", {
      id: id,
      style: styles
    }, children);
  },
    h2: function H2(_ref2) {
    var id = _ref2.id,
        children = _ref2.children;
    var styles = (0, _objectSpread2.default)({}, _components.baseFonts, {
      fontWeight: 600,
      margin: 0,
      padding: 0,
      fontSize: '30px'
    });
    return _react.default.createElement("h2", {
      id: id,
      style: styles
    }, children);
  },
    h3: function H3(_ref3) {
    var id = _ref3.id,
        children = _ref3.children;
    var styles = (0, _objectSpread2.default)({}, _components.baseFonts, {
      fontWeight: 600,
      margin: 0,
      padding: 0,
      fontSize: '22px',
      textTransform: 'uppercase'
    });
    return _react.default.createElement("h3", {
      id: id,
      style: styles
    }, children);
  },
    h4: function H4(_ref4) {
    var id = _ref4.id,
        children = _ref4.children;
    var styles = (0, _objectSpread2.default)({}, _components.baseFonts, {
      fontWeight: 600,
      margin: 0,
      padding: 0,
      fontSize: '20px'
    });
    return _react.default.createElement("h4", {
      id: id,
      style: styles
    }, children);
  },
    h5: function H5(_ref5) {
    var id = _ref5.id,
        children = _ref5.children;
    var styles = (0, _objectSpread2.default)({}, _components.baseFonts, {
      fontWeight: 600,
      margin: 0,
      padding: 0,
      fontSize: '18px'
    });
    return _react.default.createElement("h5", {
      id: id,
      style: styles
    }, children);
  },
    h6: function H6(_ref6) {
    var id = _ref6.id,
        children = _ref6.children;
    var styles = (0, _objectSpread2.default)({}, _components.baseFonts, {
      fontWeight: 400,
      margin: 0,
      padding: 0,
      fontSize: '18px'
    });
    return _react.default.createElement("h6", {
      id: id,
      style: styles
    }, children);
  },
    li: function LI(_ref2) {
    var children = _ref2.children;
    var style = (0, _objectSpread2.default)({}, _components.baseFonts, {
      fontSize: '15px'
    });
    return _react.default.createElement("li", {
      style: style
    }, children);
  },
    p: function P(_ref) {
    var children = _ref.children;
    var style = (0, _objectSpread2.default)({}, _components.baseFonts, {
      fontSize: '15px'
    }); // <P> is oftentimes used as a parent element of
    // <a> and <pre> elements, which is why <div>
    // is used as the outputted element when parsing
    // marksy content rather than <p>.
  
  return _react.default.createElement("div", {
      style: style
    }, children);
  },
    ul: function UL(_ref3) {
    var children = _ref3.children;
    var style = (0, _objectSpread2.default)({}, _components.baseFonts, {
      fontSize: '15px'
    });
    return _react.default.createElement("ul", {
      style: style
    }, children);
  }
  }}
  context={{
    kind: 'Common/Button',
    parameters: {
      fileName: './src/components/Button/Button.stories.tsx'
    },
    story: 'submit'
  }}
  excludedPropTypes={[]}
  info="
    ### Notes

    It's a simple submit button.

    ### Usage

    ~~~js
    <Button type=&quot;submit&quot;>Submit</Button>
    ~~~"
  maxPropArrayLength={3}
  maxPropObjectKeys={3}
  maxPropStringLength={50}
  maxPropsIntoLine={3}
  propTables={[]}
  propTablesExclude={[]}
  showHeader
  showInline
  showSource={false}
  styles={function (s) {
      return (0, _nestedObjectAssign.default)({}, s, options.styles);
    }}
>
  <Button type="submit">
    Submit
  </Button>
</Story>
```

**Comment by davidyeiser** [comment]
Do you have to import `wInfo` from somewhere?

I have this code:

    storiesOf('Avatar', module)
      .addWithJSX('Default',
        wInfo(`show me please`)
        (() =>
          <Avatar
            avatarImageUrl={avatarImageUrl}
            avatarName={text('Name', 'Jennifer VanAnderson')}
          />
        ),
        {template: `
          <Avatar
            avatarImageUrl={avatarImageUrl}
            avatarName={text('Name', 'Jennifer VanAnderson')}
          />
        `}
      )

Which throws this error:

    wInfo is not defined
        ReferenceError: wInfo is not defined
        at Module.<anonymous> (http://localhost:9001/static/iframe.bundle.js:97186:85)
        at Module../src/components/Avatar/Avatar.stories.js (http://localhost:9001/static/iframe.bundle.js:97198:30)
        at __webpack_require__ (http://localhost:9001/static/iframe.bundle.js:725:30)
        at fn (http://localhost:9001/static/iframe.bundle.js:102:20)
        at webpackContext (http://localhost:9001/static/iframe.bundle.js:96991:9)
        at http://localhost:9001/static/iframe.bundle.js:874:12
        at Array.forEach (<anonymous>)
        at loadStories (http://localhost:9001/static/iframe.bundle.js:873:27)
        at ConfigApi._renderMain (http://localhost:9001/static/iframe.bundle.js:11117:20)
        at render (http://localhost:9001/static/iframe.bundle.js:11072:17)

**Comment by Regaddi** [comment]
Ah sure, forgot to mention the import:

```javascript
import { wInfo } from '../../utils';
```

and `utils.ts`

**Comment by hipstersmoothie** [comment]
@Regaddi @davidyeiser @kevinbarabash anything actionable here or can i close?

**Comment by Regaddi** [comment]
@hipstersmoothie
I haven't had much contact with storybook lately. If it helps I can create a reproduction repository demonstrating the issue.
If I remember correctly the code shown in the source panel was not the real source code for the story and had a lot of generated additions in it.

**Comment by hipstersmoothie** [comment]
Yeah a repro repo would be perfect

**Comment by Regaddi** [comment]
There we go: https://github.com/Regaddi/storybook-with-info-output-reproduction

With most recent versions of storybook and addons the original case is not reproducible anymore for me.
The only thing I noticed is an additional `onClick` prop, which is not part of the original source.

```jsx
<Button type="submit">Hello Button</Button>
```

vs.

```jsx
<Button
  onClick={function onClick() {}}
  type="submit"
>
  Hello Button
</Button>
```

But overall combining info and jsx addons seems to work just fine.
